### ISSUE TITLE
XSS Issue caused by text/template use.

### ISSUE THREAD

**Issue by s-rah** [pedronasser/caddy-search#10]
Hi,

There is an XSS issue in this extension, caused by the use of text/template instead of html/template. (See https://golang.org/pkg/html/template/#pkg-overview)

To reproduce simply launch a caddy server with search enabled, and enter the query e.g. `">HELLO` which will produce a broken output. You can try `<script>alert(0)</script>` for a nice popup.

On it's own this isn't very devastating, but combined on a larger caddy hosted site this could cause an issue.

Thanks,
Sarah

**Comment by mholt** [comment]
Thanks for the report Sarah!

This plugin probably needs an overhaul entirely; I've been trying to find someone who would be willing to do it. This should definitely get fixed as part of that (or before then).
