### ISSUE TITLE
Search results always returns empty results

### ISSUE THREAD

**Issue by mitjafelicijan** [pedronasser/caddy-search#14]
I have downloaded Caddy 0.9.2 with search extension and I am having problems with configuring search. Search always return "Found 0 results for". Is there problem with my configuration file or am I missing something. Only index.html is parsed.

My caddy.conf file contents:

```
0.0.0.0:2020
tls off
gzip
root ./html
search / {
    datadir ./tmp
}
```

Directory structure:
http://imgur.com/a/g448f

Boltbrowser output:
http://imgur.com/a/dpjWm

I am using Debian Jessy.

**Comment by mitjafelicijan** [comment]
I figured it out.

Html files you want indexed need to have `<title>Title</title>` tag present in source.

**Comment by pepa65** [comment]
Isn't that a bug?? Why is the title tag required for a search indexing?

**Comment by mholt** [comment]
There isn't a way to show results for pages without titles (yet). This plugin needs to be rewritten. :)
