### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by jungle-boogie** [pedronasser/caddy-search#6]
See: https://github.com/mholt/caddy/issues/363

Full log:
http://termbin.com/531v

Excerpt:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x54e267]
```

Replication steps:
0. start caddy
1. browse to site
2. click in a directory
3. remove file
4. refresh browser
5. observe file is gone and 404 message is present
6. go back/up one directory and see caddy crash

You may need to go to root level and back into sub-directory to cause crash. Refreshing the page may also be necessary.

caddyfile:

```
 % cat caddyfile
:2020
gzip {
level 9
}
log access.log
log error.log
ext .txt .csv
browse
search
root ../
```

I'm using the binary generated for freebsd 64 bit with hugo and search.

**Comment by pedronasser** [comment]
Wow, thanks for notifying it. I'll take look.

Note: I'm currently working on a new approach for indexing on this [branch](https://github.com/pedronasser/caddy-search)
I'll check if this issue exists their too

**Comment by pedronasser** [comment]
I couldn't replicate the panic.
But I think this commit d08969fd9ba27ffb77cb140961ae35c269dafc9c fixes it.
Could you please update your caddy-search and check if the issue is gone?

**Comment by jungle-boogie** [comment]
Hi @pedronasser,

Thanks for checking into this!

If I get a new download from http://caddyserver.com/download, will it pull from the tip of your repo?

**Comment by mholt** [comment]
@jungle-boogie No, that's a dependency nightmare. :smile: Instead you can pull the latest of his repo locally and use [caddyext](https://github.com/caddyserver/caddyext) to try the updated plugin.

**Comment by pedronasser** [comment]
@jungle-boogie:

You can build caddy with caddy-search locally like this:

```
go get -u github.com/mholt/caddy
go get -u github.com/caddyserver/caddyext
caddyext install -u search
caddyext move search 8
cd $GOPATH/src/github.com/mholt/caddy
go build -o caddy-custom
```

**Comment by jungle-boogie** [comment]
Hello,

I do think this is resolved. I built your search and then caddy with search.

Thanks!
